qmake sucks. Adding '' to the cli args does not mean compile the current directory.
git-svn-id: svn+ssh://svn.last.fm/svn/clientside/trunk/desktop@118234 ab8f4a45-97f9-0310-bbd1-854ce3dcee89

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -165,13 +165,13 @@ else
         fi;;
             
         Linux)
-            qmake -config debug -recursive Last.fm.pro "CONFIG += warn_off" "$EXTRA_QMAKE_FLAGS" || die "Configure failed."
+            qmake -config debug -recursive Last.fm.pro "CONFIG += warn_off" || die "Configure failed."
             BUILD_CMD='make'
             middle "Configured to produce a _debug_ build.";;
 
         *)
             svn co svn+ssh://gimli.last.fm/svn/clientside/bin/win _bin
-            qmake -recursive -tp vc Last.fm.pro "CONFIG -= flat" "$EXTRA_QMAKE_FLAGS" || die "Configure failed."
+            qmake -recursive -tp vc Last.fm.pro "CONFIG -= flat" || die "Configure failed."
             fix_sln
             BUILD_CMD='devenv /useenv Last.sln';;
     esac
