More of the same
git-svn-id: svn+ssh://svn.last.fm/svn/clientside/trunk/desktop@125295 ab8f4a45-97f9-0310-bbd1-854ce3dcee89

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -134,8 +134,8 @@ else
             if [ -z "$EXTRA_QMAKE_FLAGS" ]; then
                 EXTRA_QMAKE_FLAGS='NOOP=""'
             fi
-        
-            qmake -config debug -recursive Last.fm.pro "$EXTRA_QMAKE_FLAGS" || die "Configure failed."
+
+            qmake -config debug -recursive Last.fm.pro "CONFIG -= app_bundle" "$EXTRA_QMAKE_FLAGS" || die "Configure failed."
             BUILD_CMD='make'        
         fi;;
             
